name: Cron Build & Test

on:
  schedule:
    - cron:  '0 1 * * *' # Run at 01:00 Everyday

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make install
    - name: Run test
      run: make test
